= How to contribute

This document will eventually outline all aspects of guidance to make
your contributing experience a fruitful and enjoyable one.
What it already contains is information about _commit message formatting_
and how that directly affects the numerous automated processes that are used
for this repo.
It also covers how to contribute to this _formula's documentation_.

// This `toc` will not show up in GitHub directly, only in the GitHub pages.
// Antora applies all of the `toc` settings when rendering the HTML.
toc::[]

== Overview

Submitting a pull request is more than just code!
To achieve a quality product,
the _tests_ and _documentation_ need to be updated as well.
An excellent pull request will include these in the changes,
wherever relevant.

[#commit_message_formatting]
== Commit message formatting

Since every type of change requires making Git commits,
we will start by covering the importance of ensuring that
all of your commit messages are in the correct format.

[#automatic_version_bump]
=== Automation of multiple processes

This formula uses
https://github.com/semantic-release/semantic-release[semantic-release]
for automating numerous processes such as
bumping the version number appropriately,
creating new tags/releases
and updating the changelog.
The entire process relies on the structure of commit messages to
determine the version bump,
which is then used for the rest of the automation.

Full details are available in the upstream docs regarding the
https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines[Angular
Commit Message Conventions].
The key factor is that the first line of the commit message must follow this format:

.Commit message format
[source%nowrap,]
----
type(scope): subject
----

* E.g. `docs(contributing): add commit message formatting instructions`.

Besides the version bump,
the changelog and release notes are formatted accordingly.
So based on the example above:

____
+++<h3>Documentation</h3>+++

* *contributing:* add commit message formatting instructions
____

* The `type` translates into a `Documentation` sub-heading.
* The `(scope):` will be shown in bold text without the brackets.
* The `subject` follows the `scope` as standard text.

=== Linting commit messages in Travis CI

This formula uses
https://github.com/conventional-changelog/commitlint[commitlint]
for checking commit messages during CI testing.
This ensures that they are in accordance with the `semantic-release` settings.

For more details about the default settings,
refer back to the `commitlint`
https://conventional-changelog.github.io/commitlint/#/reference-rules[reference
rules].

[#commit_type_vs_version_bump]
=== Relationship between commit type and version bump

This formula applies some customisations to the defaults,
as outlined in the table below, based upon the
https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type[type]
of the commit:

[cols=",,,^,^",options="header",]

.Commit type vs. version bump
[format="psv", separator="|", frame="all", grid="all", float="left", options="header", cols="<.<14m,<.<25d,<.<37d,^.<12m,^.<12m", width="100"]
|===
^.^|Type
^.^|Heading
^.^|Description
^.^|Bump (default)
^.^|Bump (custom)

|build 
|Build System 
|Changes related to the build system 
|– 
|

|chore 
|– 
|Changes to the build process or auxiliary tools
and libraries such as documentation generation 
|– 
|

|ci 
|Continuous Integration 
|Changes to the continuous integration configuration 
|– 
|

|docs 
|Documentation 
|Documentation only changes 
|– 
|0.0.1

|feat 
|Features 
|A new feature 
|0.1.0 
|

|fix 
|Bug Fixes 
|A bug fix 
|0.0.1 
|

|perf 
|Performance Improvements 
|A code change that improves performance 
|0.0.1 
|

|refactor 
|Code Refactoring 
|A code change that neither fixes a bug nor adds a feature 
|– 
|0.0.1

|revert 
|Reverts 
|A commit used to revert a previous commit 
|– 
|0.0.1

|style 
|Styles 
|Changes that do not affect the meaning of the code
(white-space, formatting, missing semi-colons, etc.) 
|– 
|0.0.1

|test 
|Tests 
|Adding missing or correcting existing tests 
|– 
|0.0.1
|===

=== Use `BREAKING CHANGE` to trigger a `major` version change

Adding `BREAKING CHANGE` to the footer of the extended description of the
commit message will *always* trigger a `major` version change,
no matter which type has been used.
This will be appended to the changelog and release notes as well.
To preserve good formatting of these notes,
the following format is prescribed:

* `BREAKING CHANGE: <explanation in paragraph format>.`

An example of that:

.Example of supplying `BREAKING CHANGE` in a commit message
[source%nowrap, git]
----
...

BREAKING CHANGE: With the removal of all of the `.sls` files under
`template package`, this formula no longer supports the installation of
packages.
----

[#documentation]
== Documentation

.This section refers to the _Read the Docs_ documentation
[WARNING]
====
This section is relevant to the _Read the Docs_ documentation
that currently exists while this _Antora_ solution is being evaluated.
====

=== Toolchain

The documentation for this formula is written in
https://en.wikipedia.org/wiki/ReStructuredText[reStructuredText]
(also known as RST, ReST, or reST).
It is built by
https://en.wikipedia.org/wiki/Sphinx_(documentation_generator)[Sphinx]
and hosted on https://en.wikipedia.org/wiki/Read_the_Docs[Read the Docs].

=== Adding a new page

Adding a new page involves two steps:

. Use the
xref:#saltstack_formulas_rst_page_template[provided page template]
to create a new page.
. Add the page name under the `toctree` list in `index.rst`.
.. Do not just append it to the list.
.. Select the best place where it fits within the overall documentation.

=== SaltStack-Formulas' RST page template

Use the following template when creating a new page.
This ensures consistency across the documentation for this formula.
The heading symbols have been selected in accordance to the
output rendered by the
https://github.com/miyakogi/m2r#restrictions[Markdown to
reStructuredText converter]
we are using for some of the pages of this documentation.

[#saltstack_formulas_rst_page_template]
.RST page template
[source%nowrap, rst]
----
.. _template: # <1>

[Page title] # <2>
============

[Introductory paragraph] # <3>

.. contents:: **Table of Contents** # <4>

[Heading 2] # <5>
-----------

[Heading 3] # <5>
^^^^^^^^^^^

[Heading 4] # <5>
~~~~~~~~~~~

[Heading 5] # <6>
"""""""""""

[Heading 6] # <6>
###########
----

<1> The first line is an anchor that can be used to link back to
(the top of) this file.
* Change this to be the lowercase version of the file name.
* Do not include the `.rst` file extension.
* Use hyphens (`-`) instead of spaces or non-letter characters.

<2> Change the `[Page title]` accordingly.
Match the same number of equals signs (`=`) underneath.

<3> Change the `[Introductory paragraph]` to be
a short summary of the page content.
Use no more than three paragraphs for this.

<4> Leave the `..contents:: **Table of Contents**` line as it is.

<5> Use the remaining headings as required to break up the page content.
Again, no single heading should have more than about
three paragraphs of content before the next heading or sub-heading is used.

<6> You will rarely need to use beyond `[Heading 4]`.

Obviously, it is not necessary to follow the steps in the order above.
For example, it is usually easier to write the `[Introductory paragraph]`
at the end.
