= template-formula

https://travis-ci.com/saltstack-formulas/template-formula[image:https://travis-ci.com/saltstack-formulas/template-formula.svg?branch=master[Travis CI Build Status]]
https://template-formula.readthedocs.io/en/latest/?badge=latest[image:https://readthedocs.org/projects/docs/badge/?version=latest[Documentation Status]]
https://github.com/semantic-release/semantic-release[image:https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg[Semantic Release]]

A SaltStack formula that is empty.
It has dummy content to help with a quick start on a new formula and it serves
as a style guide.

// This `toc` will not show up in GitHub directly, only in the GitHub pages.
// Antora applies all of the `toc` settings when rendering the HTML.
toc::[]

== General notes

See the full
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html[SaltStack
Formulas installation and usage instructions].

If you are interested in writing or contributing to formulas,
please pay attention to the
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas[Writing
Formula Section].

If you want to use this formula, please pay attention to the `FORMULA`
file and/or `git tag`, which contains the currently released version.
This formula is versioned according to http://semver.org/[Semantic
Versioning].

See
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#versioning[Formula
Versioning Section]
for more details.

== Contributing to this repo

*Commit message formatting is significant!!*

Please see
xref:ROOT:CONTRIBUTING.adoc[How to contribute]
for more details.

== Available states

=== `template`

_Meta-state (this is a state that includes other states)_.

This installs the template package,
manages the template configuration file
and then starts the associated template service.

=== `template.package`

This state will install the template package only.

=== `template.config`

This state will configure the template service
and has a dependency on `template.install` via. the `include` list.

=== `template.service`

This state will start the template service
and has a dependency on `template.config` via. the `include` list.

=== `template.clean`

_Meta-state (this is a state that includes other states)_.

This state will undo everything performed in the `template` meta-state
in reverse order,
i.e. stops the service,
removes the configuration file
and then uninstalls the package.

=== `template.service.clean`

This state will stop the template service and disable it at boot time.

=== `template.config.clean`

This state will remove the configuration of the template service
and has a dependency on `template.service.clean` via. the `include` list.

=== `template.package.clean`

This state will remove the template package
and has a depency on `template.config.clean` via. the `include` list.
