# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# yamllint disable rule:comments
name: Commitlint
'on': [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable rule:line-length
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6
